### ISSUE TITLE
Change the makefile to name the binary jeffersonize

### ISSUE THREAD

**Issue by saulalbert** [HiLabTufts/jeffersonize#2]
and remove any other references to 'converter' in the comments etc.

**Comment by mumair01** [comment]
Running 'make' now produces a binary named 'jeffersonize'. The run command has also been changed to ./jeffersonize XXX XXX. Any error messages now refer to the program as jeffersonize instead of converter. 
Feel free to close the issue if all problems have been resolved.

**Comment by saulalbert** [comment]
Brilliant - looks good.
