### ISSUE TITLE
Change the file extension '.ca' to '.ca.cha' so that it opens in CLAN automatically

### ISSUE THREAD

**Issue by saulalbert** [HiLabTufts/jeffersonize#3]
Since CLAN's installer already associates .cha files with CLAN, it's probably better to keep the '.cha' filename, but instead add a '.ca.' to the middle of the filename. So if you run KB0RE000.cha through jeffersonize, it should come out as KB0RE000.ca.cha. Converting the other way should just remove the 'ca' bit.

**Comment by mumair01** [comment]
One aspect to consider here is that talk ban's chat2ca script generates a ca file with the .S.ca extension. This causes CLAN to open it in Text mode such that using check is no longer allowed, which makes sense. changing the extension to .S.ca.cha will cause CLAN to open the file in normal mode. In this case, if the user runs check, it detects multiple problems in the CA file.
Shall I still proceed to change the extension?

**Comment by saulalbert** [comment]
Ah. I didn't realize that. No - if chat2ca already generates a .S.ca extension perhaps we should stick with that. I don't think it's a problem that CHECK doesn't work since we don't really expect it to work with a .ca file do we... just with the resulting .cha file. So - just leave this as it is for now then.
