### ISSUE TITLE
Custom indent function

### ISSUE THREAD

**Issue by mumair01** [HiLabTufts/jeffersonize#6]
The custom indent script initially part of Jeffersonize failed to have satisfactory performance in many cases i.e. the indents were not in line, or it couldn't handle multiple indents.
As such, I decided to replace our custom indent feature with Talk-Bank's indent script. However, this means that the indent binary is not a dependency for the jeffersonize  script.
Is this an acceptable update?

**Comment by saulalbert** [comment]
I think I understand from this that CLAN's INDENT feature *is* a dependency (you say it's not a dependency). Do I understand correctly?

**Comment by saulalbert** [comment]
Yes that makes sense, we can just include instructions about how to use INDENT.
